### ISSUE TITLE
error occured when trainning the model

### ISSUE THREAD

**Issue by gtrhythm** [ZhenboSong/mono_velocity#1]
I'm trying to run the model on both pytorch 1.1.0. and pytorch 0.4( the recommended enviroment)

**The code could not even be initialized in pytorch 0.4** ---- error occured when running setup.py in the folder 'correlations'.

**When switch version of pytorch from 0.4 to 1.1.0, the code could be initialized** (the setup.py could be installed successfully).

With the given testing code, the model work well in the enviroment. However, error occured when I was trying to train it, which is shown below:
```
Traceback (most recent call last):
  File "train_crop_velocity.py", line 188, in <module>
    main()
  File "train_crop_velocity.py", line 184, in main
    model.train()
  File "train_crop_velocity.py", line 112, in train
    res = self.model(data)
  File "/data/wangyuchen/anaconda3/envs/pytorch/lib/python3.6/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/data/wangyuchen/mono_velocity/networks/cropvelocity.py", line 55, in forward
    corr6 = self.corr(c16, c26)
  File "/data/wangyuchen/anaconda3/envs/pytorch/lib/python3.6/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/data/wangyuchen/mono_velocity/networks/correlation/correlation.py", line 68, in forward
    result = CorrelationFunction.apply(input1, input2, self.pad_size, self.kernel_size, self.max_displacement,self.stride1, self.stride2, self.corr_multiply)
**TypeError: save_for_backward can only save variables, but argument 2 is of type int**
```

It seems that the function save_for_backward could not store integer value.

When I shift those int value from int to a 0-dimension tensor,  the forward function wored well. However, an error occured on the when backward operation was applied:
```
data processing Croper train
Use a dataset with 74 images
data processing Croper train
Use a dataset with 1000 images
Val_loss: 0.018639859693074547
Traceback (most recent call last):
  File "train_crop_velocity.py", line 188, in <module>
    main()
  File "train_crop_velocity.py", line 184, in main
    model.train()
  File "train_crop_velocity.py", line 135, in train
    v_z_loss.backward()
  File "/data/wangyuchen/anaconda3/envs/pytorch/lib/python3.6/site-packages/torch/tensor.py", line 107, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/data/wangyuchen/anaconda3/envs/pytorch/lib/python3.6/site-packages/torch/autograd/__init__.py", line 93, in backward
    allow_unreachable=True)  # allow_unreachable flag
**RuntimeError: function CorrelationFunctionBackward returned an incorrect number of gradients (expected 8, got 2)**
```
I have tried to shift those int value to tensor when function 'save_for_backward' is applied and, when it comes to excute the forward and backward function,  shift them from tensor to int, however, nothing changed.

How could I solve the question?

**Comment by Amrsaeed** [comment]
Not the author but I faced the same issue. 
You have two options: Either convert the int values to tensor like you did or save them to the ctx directly not using save_for_backward
In both cases, in the backward function, the return arguments must equal the inputs to the forward function. Given that those values are ints anyway and not variables, you can just return None for each of them and it should work with you.

Reference: https://discuss.pytorch.org/t/how-to-save-a-list-of-integers-for-backward-when-using-cpp-custom-layer/25483
